### PR TITLE
Add link to Vite

### PR DESCRIPTION
**Pull request by BurntCaramel**
**Repo URL:** https://github.com/vitejs/vite

**Twitter Username:** `@concreteniche`

**Description:** Fast dev server via on-demand ES modules for Preact, React, or Vue; uses Rollup for production builds.

### CODE REVIEW

**Comment by rschristian** [comment]
Vite is a build tool, not really a toolkit. If you look at the others on that list they have some amount of specialization. 

Vite is an alternative to Webpack or Rollup, not the Preact Cli, NWB, React App Rewire Preact, etc.

**Comment by BurntCaramel** [comment]
Interesting! I would see it as a direct competitor to Preact CLI, NWB, etc. I wouldn’t use Vite and one of these. And Vite wraps Rollup in a similar way that Preact CLI wraps Webpack.

**Comment by rschristian** [comment]
Sure, but the CLI, NWB, etc. add Preact-specific content.

Vite is general use, so you can run it with pretty much any library, so I can't say I'd see how that would be "Awesome Preact"?

Do you think Webpack, Rollup, Parcel, and etc. should be added too?

**Comment by BurntCaramel** [comment]
It’s the Preact template specifically that’s of interest, it’s nested inside this repo: https://github.com/vitejs/create-vite-app/tree/master/template-preact

You use it like so:

```console
npm init vite-app <project-name> --template preact
```

I think this is different to Webpack, Rollup etc. I think it’s a viable alternative to Preact CLI and NWB (both of which I’ve used and think are great projects). In fact, I think it’s awesome!

But I don’t mean to waste time here, so the choice is up to you.

**Comment by rschristian** [comment]
Now that I could definitely see.

Not my choice either! Not a core member or anything. Was just taking a peek through

**Comment by ooade** [comment]
@BurntCaramel This is good. What do you think about using the description:

```
Fast native-ESM powered web dev build tool.
```

As used on vite's documentation.

**Comment by BurntCaramel** [comment]
@ooade Have updated to use that description.

**Review by ooade — APPROVED** [review]

**Pull request merged**
